import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    chineseSidebar: [
        {
            type: 'category',
            label: 'Chinese Learning',
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'chinese',
                },
            ],
        },
    ]
};

export default sidebars;

